# Kustomize replacements for SecretProviderClass
# This file is processed by a script to inject actual values from infra_version.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - source:
      kind: ConfigMap
      name: infra-config
      fieldPath: data.rds_secret_arn
    targets:
      - select:
          kind: SecretProviderClass
          name: db-secret-provider
        fieldPaths:
          - spec.parameters.objects.[objectName="${RDS_SECRET_ARN}"].objectName
  - source:
      kind: ConfigMap
      name: infra-config
      fieldPath: data.secrets_manager_role_arn
    targets:
      - select:
          kind: ServiceAccount
          name: backend-sa
        fieldPaths:
          - metadata.annotations.eks\.amazonaws\.com/role-arn

